#!/bin/bash
# 10-install-service-files.sh — install the repo's vLLM unit + launcher onto the T5810,
# fixing the OpenRC export bug. PURE PLUMBING: no engine behaviour changes.
#
# WHAT WAS BROKEN. /etc/init.d/vllm-qwen38 sources /etc/conf.d/vllm-qwen38 (OpenRC does that
# automatically) and uses the values inside the init script, but never EXPORTS them.
# supervise-daemon then execs the launcher as a child, and a child inherits only exported
# variables. Measured 2026-09-12 on a process up 8d23h:
#     tr '\0' '\n' < /proc/<pid>/environ | grep -c '^VLLM_'   ->   0
# Every variable the launcher reads has its own `: "${VAR:=default}"` fallback and each one
# happened to equal conf.d, so this was invisible. The exception is VLLM_EXTRA_ARGS, which has
# no launcher default and exists solely to change behaviour: `--enable-prefix-caching` sat in
# conf.d from 2026-08-31 to 2026-09-12 and reached nothing.
#
# WHY VLLM_PORT IS NOT JUST EXPORTED WITH THE REST. VLLM_PORT is also a real vLLM environment
# variable (vllm/envs.py): "used in distributed environment to manually set the communication
# port ... if some code asks for multiple ports, VLLM_PORT will be used as the first port, and
# the rest will be generated by incrementing". Exporting VLLM_PORT=8007 would hand the engine's
# internal allocator a base of 8007 and walk it into 8008/8009 — the sibling backend slots.
# The launcher now takes the serving port as VLLM_SERVE_PORT and unsets VLLM_PORT before exec.
#
# WHAT THIS DOES TO PREFIX CACHING (changed 2026-09-13 -- the earlier header said the
# opposite and was left stale for a few hours). The launcher installed here carries
# `--enable-prefix-caching` in its permanent argv, so running this KEEPS prefix caching on
# while moving it out of conf.d's VLLM_EXTRA_ARGS. That matters: VLLM_EXTRA_ARGS is the
# EXPERIMENT slot, it is meant to be reverted, and while it is occupied
# 09-vllm-experiments.sh refuses to start -- which currently blocks the ngram experiment.
# Net effect: same engine behaviour, correct mechanism, slot freed.
#
# To turn prefix caching OFF instead, remove the `--enable-prefix-caching` line from
# home/vllm-service/start-qwen38.sh before running this.
#
# THE SITE IS DOWN for the restart window (a 29 GB model load, typically 2-7 min).
#
# Usage (as root, on the T5810, from the repo root):
#   ./scripts/tuning/10-install-service-files.sh --dry-run   # show the diffs, change nothing
#   ./scripts/tuning/10-install-service-files.sh             # install + restart + assert
#   ./scripts/tuning/10-install-service-files.sh --rollback  # restore the pre-install copies
set -uo pipefail

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$REPO_DIR/home/vllm-service"
UNIT=/etc/init.d/vllm-qwen38
CONF=/etc/conf.d/vllm-qwen38
LAUNCHER=/opt/vllm-service/start-qwen38.sh
EXPBAK=/root/vllm-exp-backups
BAKDIR=/root/vllm-install-backups
LOGDIR=/home/chris/tuning-logs
PORT=8007
READY_WAIT=600
MODE="${1:-install}"

mkdir -p "$LOGDIR"
LOG="$LOGDIR/10-install-$(date +%Y%m%d-%H%M%S).log"
ln -sfn "$LOG" "$LOGDIR/10-latest.log"
exec > >(tee -a "$LOG") 2>&1

banner(){ echo; echo "=================================================================="; echo " $*"; echo "=================================================================="; }
die(){ echo "!! $*" >&2; exit 1; }

# Reject unknown modes. This script does NOT use `set -e`, and the dispatch below only tests
# for --dry-run and --rollback, so any other argument -- a typo like `--dryrun`, `-n`, or
# `--roll-back` -- fell through to the LIVE INSTALL path and restarted production. Validated
# here rather than at the MODE assignment because `die` has to exist first.
case "$MODE" in
    install|--dry-run|--rollback) ;;
    *) die "unknown mode: '$MODE'   (expected: --dry-run | --rollback | no argument)" ;;
esac

# --dry-run reads only world-readable files, so it needs no root: the diffs should be
# reviewable before anyone types sudo.
[ "$MODE" = "--dry-run" ] || [ "$(id -u)" -eq 0 ] || die "must run as root (sudo). Try --dry-run first."
for f in "$SRC/vllm-qwen38.openrc" "$SRC/start-qwen38.sh"; do
    [ -f "$f" ] || die "missing repo file: $f"
done

wait_ready() {
    # $1 = pid before the restart. A restart that silently did nothing returns
    # "ready after 0s" because the OLD process is still serving — that is exactly how the
    # 2026-08-31 prefix experiment reported a pass having changed nothing.
    local want_new="${1:-}" w=0 now
    printf "  waiting for :%s " "$PORT"
    while [ "$w" -lt "$READY_WAIT" ]; do
        if curl -sf -m 5 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then
            now=$(pgrep -f "bin/vllm serve" | head -1)
            if [ -n "$want_new" ] && [ "$now" = "$want_new" ]; then
                printf "!"; sleep 10; w=$((w+10)); continue   # old process, not a restart
            fi
            echo " ready after ${w}s (pid ${now:-?})"; return 0
        fi
        printf "."; sleep 10; w=$((w+10))
    done
    echo " TIMEOUT after ${w}s"; return 1
}

restart_and_assert() {
    echo; echo "--- restarting vLLM (THE SITE IS DOWN for this window) ---"
    local oldpid; oldpid=$(pgrep -f "bin/vllm serve" | head -1); echo "  pid before: ${oldpid:-none}"
    rc-service vllm-qwen38 restart 2>&1 | sed 's/^/    /'
    wait_ready "$oldpid" || return 1

    local pid; pid=$(pgrep -f "bin/vllm serve" | head -1)
    echo; echo "--- assert against LIVE state, never the file we edited ---"
    local n_vllm
    n_vllm=$(tr '\0' '\n' < "/proc/$pid/environ" | grep -c '^VLLM_' || true)
    echo "  VLLM_* vars in /proc/$pid/environ: $n_vllm   (was 0 before this fix)"
    [ "$n_vllm" -gt 0 ] || { echo "  !! still zero — the export did not take"; return 1; }
    tr '\0' '\n' < "/proc/$pid/environ" | grep '^VLLM_' | sed 's/^/      /'

    if tr '\0' '\n' < "/proc/$pid/environ" | grep -q '^VLLM_PORT='; then
        echo "  !! VLLM_PORT is in the engine environment — it would rebase internal ports"
        return 1
    fi
    echo "  VLLM_PORT absent from the engine environment: correct"

    local served; served=$(tr '\0' '\n' < "/proc/$pid/cmdline" | grep -A1 -- '--port' | tail -1)
    echo "  --port in live argv: ${served:-?}"
    [ "$served" = "$PORT" ] || { echo "  !! serving port is not $PORT"; return 1; }

    echo "  engine config as RESOLVED:"
    grep -a "Initializing a V1 LLM engine" /var/log/qwen38/writer.log | tail -1 \
      | grep -oE "enable_prefix_caching=[A-Za-z]+|speculative_config=[^,]*" | sed 's/^/      /'

    local r
    r=$(curl -s -m 120 "http://127.0.0.1:$PORT/v1/completions" -H 'Content-Type: application/json' \
          -d '{"model":"qwen3.8-27b","prompt":"Reply with one word: ok","max_tokens":5,"temperature":0}' \
        | python3 -c 'import json,sys; print((json.load(sys.stdin)["choices"][0]["text"] or "").strip()[:20])' 2>/dev/null)
    [ -n "$r" ] && echo "  generation smoke: PASS -> \"$r\"" || { echo "  !! generation FAILED"; return 1; }

    echo "  labrouter through the contract port:"
    curl -s -m 10 http://127.0.0.1:8004/health | sed 's/^/      /'
}

# Exit codes are the contract, because a human reads the banner but automation reads $?:
#   0  rolled back (or --rollback requested) and the service came back
#   1  rolled back after a failed install; service is healthy but the install did NOT apply
#   2  RESTORED THE FILES BUT THE SERVICE DID NOT COME BACK — needs a human, now
# The previous version printed a warning and exited 0 in the case that matters most, so a
# caller could not tell a clean rollback from a dead backend.
rollback() {
    local rc="${1:-0}"
    banner "ROLLBACK — restoring the pre-install copies"
    [ -d "$BAKDIR" ] || die "no backup directory $BAKDIR — nothing to roll back"
    for f in vllm-qwen38.unit:"$UNIT" vllm-qwen38.conf:"$CONF" start-qwen38.sh:"$LAUNCHER"; do
        local n=${f%%:*} dst=${f#*:}
        if [ -f "$BAKDIR/$n" ]; then cp -a "$BAKDIR/$n" "$dst"; echo "  restored $dst"; fi
    done
    if restart_and_assert; then
        echo "  rolled back and serving"
        exit "$rc"
    fi
    echo "!! ROLLBACK RESTORED THE FILES BUT THE SERVICE DID NOT COME BACK." >&2
    echo "   This is the bad case: pre-install files are on disk and :$PORT is not answering." >&2
    echo "   Check /var/log/qwen38/writer.log and \`rc-service vllm-qwen38 status\`." >&2
    exit 2
}

show_diffs() {
    echo "--- $UNIT ---";     diff -u "$UNIT"     "$SRC/vllm-qwen38.openrc" || true
    echo "--- $LAUNCHER ---"; diff -u "$LAUNCHER" "$SRC/start-qwen38.sh"    || true
    echo "--- $CONF: the leftover experiment line this comments out ---"
    grep -nE '^[[:space:]]*(export[[:space:]]+)?VLLM_EXTRA_ARGS=' "$CONF" | sed 's/^/    /' \
      || echo "    (none present)"
    echo "--- $CONF: the VRAM-wait alignment this makes ---"
    if grep -qE '^[[:space:]]*VLLM_VRAM_WAIT=180[[:space:]]*$' "$CONF"; then
        grep -nE '^[[:space:]]*VLLM_VRAM_WAIT=' "$CONF" | sed 's/^/    /'
        echo "    -> VLLM_VRAM_WAIT=300. Once conf.d is exported this value also reaches the"
        echo "       LAUNCHER's VRAM wait, which is the respawn path (start_pre does not run on"
        echo "       respawn, and orphaned TP workers hold ~19 GB each). The launcher's own"
        echo "       default was already 300 with a documented crash-loop rationale, so align UP"
        echo "       rather than let the plumbing fix silently shorten the margin to 180s."
    else
        echo "    (already aligned, or not set to 180)"
    fi
}

[ "$MODE" = "--rollback" ] && rollback 0

banner "INSTALL vLLM service files — $(date)"
echo "repo: $REPO_DIR"

echo; echo "--- syntax check the repo copies BEFORE touching anything ---"
bash -n "$SRC/start-qwen38.sh" || die "launcher does not parse"
# mktemp, not /tmp/.unit-syntax.$$ : this script runs as ROOT, and $$ is guessable, so any
# local user could pre-plant a symlink at that path and have the root shell's `>` truncate a
# file of their choosing. The EXIT trap removes it on every path, including `die`.
_TMP_UNIT="$(mktemp "${TMPDIR:-/tmp}/vllm-unit-syntax.XXXXXX")" || die "mktemp failed"
trap 'rm -f "$_TMP_UNIT"' EXIT
tail -n +2 "$SRC/vllm-qwen38.openrc" > "$_TMP_UNIT" || die "cannot stage the unit for parsing"
sh -n "$_TMP_UNIT" || die "unit does not parse"
echo "  both parse"

echo; echo "--- what would change ---"
show_diffs

if [ "$MODE" = "--dry-run" ]; then
    banner "DRY RUN — nothing changed.  log: $LOG"
    exit 0
fi

echo; echo "--- backing up the CURRENT live files ---"
mkdir -p "$BAKDIR"
cp -a "$UNIT"     "$BAKDIR/vllm-qwen38.unit"
cp -a "$CONF"     "$BAKDIR/vllm-qwen38.conf"
cp -a "$LAUNCHER" "$BAKDIR/start-qwen38.sh"
echo "  -> $BAKDIR"

# The experiment harness keeps its own baseline copies and (before today) only wrote them if
# absent. Stale copies from 2026-08-31 would make the next `09-vllm-experiments.sh revert`
# restore the OLD launcher over the one being installed here, silently undoing this fix while
# printing "reverted and serving". Refresh them, keeping the old ones.
if [ -d "$EXPBAK" ]; then
    echo; echo "--- refreshing the experiment harness's baseline copies ---"
    for n in start-qwen38.sh vllm-qwen38; do
        if [ -f "$EXPBAK/$n.orig" ]; then
            mv "$EXPBAK/$n.orig" "$EXPBAK/$n.orig.pre-install-$(date +%Y%m%d-%H%M%S)"
            echo "  retired stale $EXPBAK/$n.orig"
        fi
    done
fi

echo; echo "--- installing ---"
# Both statuses are checked. Without `set -e` a failed `install` used to be swallowed by the
# `&&`, so a PARTIAL installation (new unit, old launcher, or vice versa) could reach the
# restart and be reported as a success -- the live-state assertions below do not cover every
# launcher behaviour, so the mismatch would not necessarily surface.
if ! install -o root -g root -m 0755 "$SRC/vllm-qwen38.openrc" "$UNIT"; then
    echo "!! failed to install $UNIT — rolling back rather than leaving a partial install" >&2
    rollback 1
fi
echo "  $UNIT"
if ! install -o root -g root -m 0755 "$SRC/start-qwen38.sh" "$LAUNCHER"; then
    echo "!! failed to install $LAUNCHER — the unit is already new, so this is exactly the" >&2
    echo "   partial state that must not reach a restart. Rolling back." >&2
    rollback 1
fi
echo "  $LAUNCHER"

# Strip any active VLLM_EXTRA_ARGS so this restart is a clean baseline. Keep the commented
# documentation form the repo's conf.d carries.
if grep -qE '^[[:space:]]*(export[[:space:]]+)?VLLM_EXTRA_ARGS=.' "$CONF"; then
    sed -i -E 's/^[[:space:]]*(export[[:space:]]+)?VLLM_EXTRA_ARGS=/#&/' "$CONF"
    echo "  commented out the leftover VLLM_EXTRA_ARGS in $CONF"
fi

# Once conf.d is actually exported, VLLM_VRAM_WAIT reaches the LAUNCHER as well as the unit's
# start_pre. conf.d said 180; the launcher's own default was 300, with a documented rationale
# (a respawn into a dying instance's still-held ~19 GB crash-loops, and start_pre does not run
# on respawn). Fixing the plumbing must not shorten that margin as a side effect, so align up.
if grep -qE '^[[:space:]]*VLLM_VRAM_WAIT=180[[:space:]]*$' "$CONF"; then
    sed -i -E 's/^([[:space:]]*)VLLM_VRAM_WAIT=180[[:space:]]*$/\1VLLM_VRAM_WAIT=300/' "$CONF"
    echo "  VLLM_VRAM_WAIT 180 -> 300 in $CONF (now reaches the launcher's respawn path)"
fi

echo; echo "--- values that become effective for the first time (conf.d vs launcher defaults) ---"
python3 - "$CONF" "$LAUNCHER" <<'PYCHK'
import re, sys
conf, launcher = open(sys.argv[1]).read(), open(sys.argv[2]).read()
cv = {m.group(1): m.group(2).split('#')[0].strip().strip('"\'')
      for m in re.finditer(r'^[ \t]*(?:export[ \t]+)?([A-Z_]+)=(.*)$', conf, re.M)}
dv = {m.group(1): m.group(2) for m in re.finditer(r'^[ \t]*:\s*"\$\{([A-Z_]+):=(.*?)\}"', launcher, re.M)}
diff = [(k, dv[k], v) for k, v in sorted(cv.items()) if k in dv and v != dv[k]]
for k, d, v in diff:
    print(f"    {k}: launcher default {d!r} -> conf.d {v!r}")
print("    (none — conf.d matches every launcher default, so this is pure plumbing)" if not diff else "")
PYCHK

if restart_and_assert; then
    banner "DONE — plumbing fixed, engine unchanged.
 Next:  sudo ./scripts/tuning/09-vllm-experiments.sh prefix
 Undo:  sudo $0 --rollback
 log:   $LOG"
else
    banner "ASSERTIONS FAILED — rolling back"
    rollback
fi
